package com.hadasht.study.puzzlers;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.hadasht.study.puzzlers.utils.Constants.PUZZLE_NAME;
import static com.hadasht.study.puzzlers.utils.Constants.SOLUTION_NAME;
import static org.assertj.core.api.Assertions.assertThat;

@DisplayName("EscapeRout")
class Puzzle15Test {

	@Test
	@DisplayName(PUZZLE_NAME)
	void puzzle() throws Exception {
		Puzzle15.puzzle();
	}

	@Test
	@DisplayName(SOLUTION_NAME)
	void solution() throws Exception {
		Puzzle15.solution();

	}

	public static class Puzzle15 {

		/**
		 * Generated by the IBM IDL-to-Java compiler, version 1.0
		 * from F:\\TestRoot\\apps\\a1\\units\\include\\PolicyHome.idl
		 * Wednesday, June 17, 1998 6:44:44 o'clock AM GMT+00:00
		 *
		 *
		 * <code>주석 중에 \\units 유니코드 이스케이프 시퀀스로 판단되어 컴파일 오류</code>
		 */
		public static void puzzle() {
			System.out.print("Hell");
			System.out.println("o world");
		}

		/**
		 *
		 * Generated by the IBM IDL-to-Java compiler, version 1.0
		 * from F:\\TestRoot\\apps\\a1\\units\\include\\PolicyHome.idl
		 * Wednesday, June 17, 1998 6:44:44 o'clock AM GMT+00:00
		 *
		 * 주석이라도 유니코드 이스케이프는 사용하지 않을 것을 권장함.
		 *
		 */
		public static void solution() {
			System.out.print("Hell");
			System.out.println("o world");
		}




	}
}
